# Generated by Django 4.2.7 on 2023-11-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('place_name', models.CharField(max_length=255)),
                ('formatted_address', models.TextField()),
            ],
        ),
    ]
