# Generated by Django 4.2.7 on 2023-11-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_searchhistory_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='distance',
            field=models.IntegerField(default=0),
        ),
    ]
